name: CI

on:
  push:
    branches:
      - master
      - lab6
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check files
        run: echo "CI workflow is working successfully"
